site_name: Scratch Projects

nav:
    - Home: 'index.md'
    - Boat Race:
        - Overview: boat-race/boat-race.md
        - 'Step 1: Getting started': boat-race/boat-race-step-1.md
        - 'Step 2: Controlling the boat': boat-race/boat-race-step-2.md
        - 'Step 3: Crashing!': boat-race/boat-race-step-3.md
        - 'Step 4: Winning!': boat-race/boat-race-step-4.md
        - 'Step 5: Adding a timer': boat-race/boat-race-step-5.md
        - 'Step 6: Obstacles and boosters': boat-race/boat-race-step-6.md
        - Challenge: boat-race/boat-race-challenge.md
        
      
markdown_extensions:
      - admonition
      - pymdownx.details
      - def_list
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - attr_list
      - md_in_html    
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.superfences
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
      
theme:
  name: material
  logo: assets/scratch-cat.png
  favicon: assets/scratch-cat.png
  font:
    text: Quicksand
  palette:
    scheme: default
    primary: blue
    accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    - navigation.footer
    - navigation.tabs
plugins:
  - search
  - glightbox

copyright: Copyright &copy; 2025 Pixel&Wood Computer Science Tuition

extra_css:
  - assets/custom.css
